### PR TITLE
Improved readability, used Java 8 syntax and formatted spacing

### LINKED ISSUE #1: Reformat code
Really like this!!, would you mind formatting the code/spaces etc for better readability?

### PR DESCRIPTION
**Pull request by ghost**
It may seem they were a lot of additions but it is really more spacing than anything.  I used Java 8 syntactic sugar (lambdas, etc ) since the project is built under Java 1.8:

``` java
  button.addActionListener(e -> closeMe());
```

There were some things I did not dare to change like hungarian notation around the code:

``` java
private boolean mLedMatrix[][] = new boolean[8][8];
```

Other than that, I think that will be all. Hope to see you at BSides 👍 

Fixes #1

### CODE REVIEW

**Comment by soynerdito** [comment]
good job, thanks. This code was put together in a hurry without much thinking and haven't touch it after.
I got a question. I have not run this, but is this a replacement of the one before?
 private void clearLedMatrix() {
-        for (int x = 0, y = 0; x < 8 && y < 8; x++, y++) {
-            mLedMatrix[y][x] = false;
-        }
-    }
  The same as the ugly two loops one inside the other.
  will mLedMatrix[0][1] ever be set to false? I am not used to write it like that.
  Again the matrix, is not correct in any means. This is some very ugly code that I wanted to go to bed and just wrote it because I could visualize it in that moment in time.

**Comment by ghost** [comment]
Oh, good catch and you are true mLedMatrix[0][1] will never be set to false, do you want me to rollback on it and set it like it was before?

**Comment by soynerdito** [comment]
yes, rollback. You can do was it was or other better way. Then summit to accept it.
Also why you set up the imports with the awt.\* ? Won't that add more than needed?

**Comment by ghost** [comment]
@soynerdito Done, and yeah the auto "optimize" import in IntelliJ included the awt.\* apologies.

**Review by soynerdito — APPROVED** [review]
perfect

**Pull request merged**
